apiVersion: v1
kind: Pod
metadata:
  name: code7
  labels:
    run: code7
spec:
  containers:
  - image: my-app
    name: code7
    imagePullPolicy: Never
    ports:
    - containerPort: 2000
  dnsPolicy: ClusterFirst
  restartPolicy: Always
