version: "3"
services:
  web:
    image: my-app
    ports:
       - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:8080 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: on-failure
